Talks - slides added to documentation.
solid/solidos pull request #95
Opened 2021-11-11 16:31 UTC by timbl

Work in progress
Plan is for talks on forms at least.

2021-11-11 21:34 UTC, TallTed requested changes
Fixed some typos and similar. There will be more, beyond where I got to.

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +<li>High-level design allows <b>multiple</b> compaitible implementations</li>
```suggestion
<li>High-level design allows <b>multiple</b> compatible implementations</li>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +  Forms part of the talkshould be on the web, maybe in the talk itself/examples or in other places where we have persistent curated set of examples.
```suggestion
  @@ add a really small form with just a set of questions - name string, children number, enrolled date, interested boolean.
  Forms part of the talk should be on the web, maybe examples in the talk itself, or in other places where we have persistent curated set of examples.
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +  <li>@@ add fileds
```suggestion
  <li>@@ add fields
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +<p>So e give the predicate which will be used in the instance of the field.</p>
```suggestion
<p>Each one adds (typically) a new edge to the data graph at run time.</p>
<p>So we give the predicate which will be used in the instance of the field.</p>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +<p>A group is just set of components in order</p>
```suggestion
<p>A group is just a set of components in an order</p>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +@@ on the left the form data, on the right the form rendred
```suggestion
@@ on the left the form data, on the right the form rendered
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +<p>This form field allows users to select things from lists in public databases, things like Languages, Organizations, Occupations, and Skills</p>
```suggestion
<p>This form field allows users to select things &mdash; like Languages, Organizations, Occupations, and Skills &mdash; from lists in public databases,</p>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/FormsTalk.html
> +<p>(Ther is a @@ref blog about is which I could run though if interested)</p>
```suggestion
<p>(There is a @@ref blog about it which I could run though if interested)</p>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/slidey.html
> +<li>Advance to next slide with mouse click, space bar or swipe left</li>
```suggestion
<li>Advance to next slide with mouse click, space bar, or swipe left</li>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/slidey.html
> +keys, or swipe left or right</li>
```suggestion
Cursor Right, <strong>Pg Up</strong>, or <strong>Pg Dn</strong>
keys; or swipe left or right</li>
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/slidey.html
> +table of contents, or click on "contents" on the toolbar or
```suggestion
table of contents, or click on "contents" on the toolbar, or
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/slidey.html
> +<li>Try it now to see how to include notes for handouts (this is
```suggestion
<li>Try it now, to see how to include notes for handouts (this is
```

2021-11-11 21:34 UTC, TallTed commented on documentation/talks/forms/slidey.html
> +<p>For handouts, its often useful to include extra notes using a
```suggestion
<p>For handouts, it's often useful to include extra notes using a
```

2021-12-05 08:59 UTC, timbl commented
I have abandoned this branch at the more logical place to put the talk is in solid-II

2021-12-06 18:09 UTC, closed without merging